version: '3'
services:
  app:
    image: install-python-django-in-docker
    container_name: install-python-django-in-docker
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./:/src
